title: Tony's land
email: antoine.karcher.id@gmail.com
description: >
  such wow
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: tonykero
repository: tonykero/tonykero.github.io

include:
  - _pages
  - _includes

collections:
  cours:
    output: true
    permalink: /:categories/:title

defaults:
  - {scope: {type: posts}, values: {layout: page, permalink: '/posts/:year/:month/:day/:title/'}}
  - {scope: {type: pages}, values: {layout: page}}
# Build settings
markdown: kramdown
kramdown:
  math_engine: mathjax

theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jemoji

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE
  - .gitignore